version: '3.4'

services:
  backend:
    build:
      context: ./api
      dockerfile: ./Dockerfile
    container_name: backend
    environment:
      - ENV_FILE_PATH=environments/.env.${SHORT_ENV}
      - TZ=America/Manaus
    command: bash -c "sleep 10 && alembic upgrade head && uvicorn src.api:app --host 0.0.0.0 --port 8000 --env-file environments/.env.${SHORT_ENV}"
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
    restart: 'always'

  dashboard:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile.${DOCKERFILE_SUFIX}
    container_name: frontend
    environment:
      - TZ=America/Manaus
    volumes:
      - ./frontend:/frontend
    ports:
      - 4200:80
    restart: 'always'
